/** Copy shared by the story player, tutorial, and research popovers. */
export const englishCopy: Record<string, string> = {
  "新手指引": "Tutorial", "回首页": "Home", "重新开始": "Restart", "再玩一轮": "Play again",
  "选择后页面": "Decision outcome", "变量警告页": "Resource warning", "失败结局": "Failure ending", "结局": "Ending", "剧情节点": "Story scene",
  "钱包厚度": "funds", "时间余量": "available time", "签证把握": "visa standing", "住房安稳度": "housing stability", "学业状态": "academic standing",
  "身心电量": "wellbeing", "当地语言熟练度": "local language skills", "职业筹码": "career prospects", "学术人脉": "academic network", "成绩余量": "grade margin",
  "正在加载生成好的故事...": "Loading your story...", "时空回卷": "Timeline rewind", "失败页": "Failure",
  "纯属虚构的时间线维修插曲": "A fictional timeline repair interlude",
  "现实中的签证、学业、健康与财务后果不会自动撤销；这里的回卷只服务于游戏重试。": "Real visa, academic, health, and financial consequences cannot be undone automatically. This rewind is only a game retry.",
  "这条时间线撞墙了。要不要看看宇宙准备了什么补丁？": "This timeline hit a wall. Ready to try another decision?",
  "打开失败页附赠的时空回卷": "Rewind this timeline", "你会怎么做？": "What will you do?",
  "时间线已修复": "TIMELINE REPAIRED", "正在整理故事书架…": "Loading the story shelf...",
  "暂无当前语言的故事。你可以选择目的地生成新故事。": "No stories in this language yet. Choose a destination to create one.",
  "暂时无法加载故事书架，请稍后重试。": "The story shelf could not be loaded. Please try again later.",
  "生成暂时未能完成。请检查服务配置和网络，然后重试。": "Generation could not finish. Check your service settings and connection, then try again.",
  "无法打开这个故事，请返回首页选择其他故事。": "This story could not be opened. Return home and choose another story.",
  "此故事的正文语言与当前选择不一致，请返回首页选择同语言故事。": "This story was written in a different language. Return home to choose a story in your selected language.",
  "故事的下一页不存在，请重新开始或返回首页。": "The next story page is missing. Restart or return home.",
  "开发调试": "Developer tools", "留学人生模拟器": "Future Life Simulator", "生活、学习、成长": "Live, Learn, Grow",
  "核心": "Critical", "重要": "Important", "补充": "Additional", "地点": "Location", "院校机构": "Institution", "学科专业": "Degree program", "专业名词": "Technical term", "金额": "Amount", "术语": "Term",
  "大学排名": "University ranking", "当前资料未确认带榜单名称和年份的可靠排名。": "No verified ranking with a named table and year is available in this research.",
  "学校类型": "Institution type", "所在地": "Location", "院校决策资料": "Institution facts", "项目与学位": "Program and degree",
  "申请基础": "Prerequisites", "录取与材料": "Admission and documents", "当前资料未确认完整录取条件，请核对项目官方页面。": "Complete admission requirements are not verified. Check the official program page.",
  "申请期限": "Application deadlines", "所属院系": "Department", "学制与学分": "Duration and credits", "授课语言/形式": "Language and delivery", "学费与资金": "Fees and funding", "培养与毕业": "Study and graduation", "专业决策资料": "Program facts",
  "暂时无法取得参考汇率，请以付款当日汇率为准。": "Reference rates are unavailable. Use the exchange rate on the payment date.",
  "正在换算人民币和斯里兰卡卢比…": "Converting to Chinese yuan and Sri Lankan rupees...", "参考换算": "Reference conversion", "约": "Approximately", "汇率日期": "Rate date", "仅供参考": "For reference only",
  "正文标注重要性说明": "Annotation importance", "悬停或点击红色文字查看注释": "Hover over or select red text to view notes", "为什么重要：": "Why it matters: ", "资料来源": "Sources", "查看注释": "View note",
  "查看这所大学的类型、所在地，以及带榜单名称和年份的最新可核实排名。": "See the university type, location, and verified rankings with their table and year.",
  "查看该院系所属大学的可核实背景；具体培养与录取信息见专业资料卡。": "See verified university background. The program facts cover study and admission requirements.",
  "查看该项目的学制学分、授课语言、录取条件、申请期限、费用与毕业要求。": "See program duration, credits, language, admission, deadlines, fees, and graduation requirements.",
  "本故事的留学目的地国家，其签证、居留和工作规定构成决策背景。": "The destination country. Its visa, residence, and work rules shape the decisions in this story.",
  "本故事的留学城市；当地生活成本、住房和行政办理条件会影响学生决策。": "The destination city. Living costs, housing, and administrative processes affect student decisions.",
  "地点决定适用的生活条件、行政流程和政策环境。": "Location determines living conditions, administrative processes, and applicable policies.",
  "院校和院系决定项目规则及可使用的校内资源。": "The institution and department determine program rules and campus resources.",
  "专业和学位项目决定课程结构、培养要求及后续职业方向。": "The degree program determines course structure, study requirements, and career directions.",
  "正文中的原币金额。下方换算使用最近可用的参考汇率，仅用于帮助比较成本。": "The original amount in the story. Conversions use available reference rates to help compare costs.",
  "金额会直接影响资金准备和方案比较。": "Amounts affect financial preparation and comparisons between options.",
  "欢迎上船": "Welcome aboard", "这是一趟可以重来的留学预演": "A study-abroad rehearsal you can replay",
  "嗨，我是你的临时向导小鸮。接下来我会用一分钟带你认认路：先读情境，再做选择，看看这条留学时间线会把你送到哪里。": "I'm Owl, your guide. Read each situation, make a choice, and discover where your study-abroad timeline leads.",
  "第一站 · 读情境": "First stop: the situation", "先看看此刻发生了什么": "Read what is happening now",
  "每一页正文都是一个真实流程中的关键节点。它会告诉你眼前的处境、期限与必须权衡的问题，不用急着做“标准答案”。": "Each scene represents a key step in a real process, with circumstances, deadlines, and tradeoffs to consider. Take your time.",
  "顺手查资料": "Explore the research", "红色词语都可以悬停查看": "Explore highlighted terms",
  "大学、学科、制度名词、金额和重要地点会按重要性标红。把鼠标移上去，或用键盘聚焦，就能看到解释、换算和资料来源。": "Institutions, programs, rules, amounts, and places are highlighted by importance. Hover, select, or focus them to see explanations, conversions, and sources.",
  "轮到你了": "Your turn", "选择会推动时间线": "Choices move the timeline forward",
  "这里以了解信息为目标。资源偏低会提示你查看支持建议，不会自动结束旅程；遇到严重后果，可以回看选择并再次尝试。": "The goal is to learn. Low resources prompt you to explore support, without automatically ending your journey. Review your decision and retry after a serious consequence.",
  "旅途剪影": "Scenes from the journey", "插图记录这一幕": "Illustrations capture the moment",
  "图片会呼应当前学校、城市或生活场景。同一段旅程可能复用镜头，让人物形象保持一致，也避免为了热闹而生成一大堆无关图片。": "Images reflect the school, city, or scene. Nearby scenes may share an illustration to keep the character and setting consistent.",
  "想换一种活法？": "Try another path?", "“重新开始”会清空本轮选择": "Restart resets this playthrough",
  "点它会回到故事起点，变量和路线也会一起复原。适合通关以后尝试另一种决定，看看是否会遇见不同结局。": "Restart returns to the beginning and resets resources and choices. Try different decisions and see which ending you reach.",
  "回到港口": "Back to the beginning", "“回首页”带你离开当前故事": "Home leaves the current story",
  "你可以回首页生成或打开另一所学校的留学预演。当前故事不会因为这份指引被改动。": "Return home to create or open another study-abroad story. The tutorial itself does not change your choices.",
  "准备完成": "Ready to go", "没有唯一正确的留学人生": "There is no single right journey",
  "把它当成一次低成本的沙盘推演：留意事实、比较代价，也观察自己在意什么。现在，去做第一个选择吧。": "Use this rehearsal to explore facts, compare tradeoffs, and notice what matters to you. Make your first choice when ready.",
  "跳过指引": "Skip tutorial", "上一步": "Previous", "下一步": "Next", "开始探索": "Start exploring", "也可以用 ← → 翻页，按 Esc 关闭": "Use the arrow keys to navigate or Escape to close",
  "欢迎来到留学预演室": "Welcome to your study-abroad rehearsal", "先从你真正想去的地方开始": "Start with the place you want to go",
  "嗨，我是向导小鸮。这里不是测你适不适合留学，而是把目标院校的真实流程变成一条可以试走、可以回头的时间线。": "I'm Owl, your guide. Explore a timeline based on real processes at your target university, with room to try again.",
  "第一步 · 告诉我目的地": "Step one: your destination", "按顺序选择国家、城市、学校与项目": "Choose a country, city, university, and program",
  "系统会用这些信息检索学校、签证、费用、课程和就业资料。目标越具体，后面的故事与专有名词解释就越贴近你。": "These details guide research into the university, visas, costs, courses, and careers. A specific destination makes the story and explanations more relevant.",
  "想先试玩？": "Want to try it first?", "缓存故事可以直接打开": "Open an existing story instantly",
  "这里保存已完整生成的路线，不会再次调用模型或图片接口。你可以先挑一所学校看看成品，再决定是否生成自己的。": "Completed stories can be played immediately. Explore one before deciding whether to generate your own.",
  "插图开关": "Illustrations", "决定本轮是否生成场景插图": "Choose whether to generate illustrations",
  "打开后，生成器会为关键场景、警告和结局制作插图；关闭则只生成文字，速度更快，也不会产生图片调用。": "Enable illustrations for key scenes, warnings, and endings. Text-only generation is faster and makes no image requests.",
  "选择叙事语言": "Story language", "语言也会影响主角设定与货币提示": "Language also affects character and currency references",
  "中文路线默认以中国女性为主角，并提供人民币换算；英文路线面向斯里兰卡女性，并提供相应的语言与货币参考。": "The current Chinese route uses a Chinese woman as the protagonist; the English route uses a Sri Lankan woman, with matching language and currency references.",
  "生成凭证": "Generation settings", "需要时在这里配置 API": "Configure your service if needed",
  "新生成会使用这里保存的服务配置；直接打开缓存不需要调用 API。密钥只应保存在本机配置中，不要分享在聊天或截图里。": "New stories use the saved service settings. Existing stories need no model calls. Keep credentials private.",
  "首页认识完毕": "Ready to begin", "生成后，我会在故事页继续带路": "I'll meet you inside the story",
  "完成资料选择会先看到录取信，后台同时收集资料并生成故事。进入正式故事后，小鸮会继续介绍正文、红色术语、选项、插图与失败回退。": "After choosing your profile, read the offer letter while the story is generated. I'll then introduce scenes, highlighted terms, choices, illustrations, and rewinds.",
};

export function translateCopy(text: string, language: string): string {
  return language === "zh" ? text : englishCopy[text] ?? text;
}
